import "@/scss/styles/globals.scss";
import "../scss/base/barrelBase.scss";
import "../scss/views/barrelService.scss";

import Head from "next/head";
import MainLayout from "@/components/layout/layout";

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

export default function App({ Component, pageProps }) {
  const queryClient = new QueryClient();

  return (
   <QueryClientProvider client={queryClient}>
      <MainLayout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          {/* <link
            href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
            rel="stylesheet"
          ></link>
          <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script> */}
        </Head>
        <Component {...pageProps} />
      </MainLayout>
    </QueryClientProvider>
  );
}
